#!/bin/bash

echo "Starting compilation"

g++ main.cpp Node.cpp -o main \
    `pkg-config --cflags --libs opencv4 gstreamer-1.0 gstreamer-app-1.0` \
    -I/usr/local/include \
    -L/usr/local/lib -lsioclient \
    -lboost_system -lboost_thread -lssl -lcrypto \
    -lapriltag -lpthread \
    -std=c++17 -Wall
